### ISSUE TITLE
Add `julia-actions/julia-format` for formatting the PRs

### ISSUE THREAD

**Issue by prbzrg** [SciML/.github#13]
It would be helpful to have https://github.com/julia-actions/julia-format for PRs. It can suggest format automatically, so there would be no need for manual format commits.
Also, it is very simple:
```
name: Format Suggestions
on:
  pull_request:
jobs:
  code-style:
    runs-on: ubuntu-latest
    steps:
      - uses: julia-actions/julia-format@v3
```
